import Head from 'next/head';
import HouseholdForm from '../components/HouseholdForm';
import HouseholdShow from '../components/HouseholdShow';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>RentCalc</h1>
      <HouseholdForm />
      <HouseholdShow />
    </>
  );
}
